//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Pages_Admin_Dashboard
{
    protected global::System.Web.UI.WebControls.Literal litMembers;
    protected global::System.Web.UI.WebControls.Literal litProjects;
    protected global::System.Web.UI.WebControls.Literal litEvents;
    protected global::System.Web.UI.WebControls.Literal litContacts;
    protected global::System.Web.UI.WebControls.GridView gvMembers;
    protected global::System.Web.UI.WebControls.GridView gvFeedback;
    protected global::System.Web.UI.WebControls.GridView gvContacts;
    protected global::System.Web.UI.WebControls.Literal litWelcome;
}
    