//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Pages_Admin_ManageEvents
{
    protected global::System.Web.UI.WebControls.Panel pnlMsg;
    protected global::System.Web.UI.HtmlControls.HtmlGenericControl addMsg;
    protected global::System.Web.UI.WebControls.TextBox txtTitle;
    protected global::System.Web.UI.WebControls.DropDownList ddlType;
    protected global::System.Web.UI.WebControls.TextBox txtDate;
    protected global::System.Web.UI.WebControls.TextBox txtDesc;
    protected global::System.Web.UI.WebControls.Button btnAdd;
    protected global::System.Web.UI.WebControls.GridView gvEvents;


}
   