//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

public partial class Pages_Events
{

     protected global::System.Web.UI.WebControls.Repeater rptEvents;
     protected global::System.Web.UI.WebControls.Label lblEmpty;
    
}
